# Retail Sales and Retail Use Business Registrations

# The dataset used in this project was obtained from the official U.S. Government Open Data Portal (Data.gov). The Retail Sales and Retail Use
# Business Registrations dataset originates from the State of Iowa and contains information about businesses registered for retail sales and use
# tax purposes. The dataset includes details such as business status, business location, tax type, permit issue dates, and permit cancellation dates.
# This information is valuable for analyzing business registration patterns, geographic distribution, tax classifications, and trends in business
# activity across the state. The dataset provides a reliable source for conducting exploratory data analysis (EDA) and generating insights that can
# support business and economic decision-making.

<!-- # The dataset used in this project was obtained from the official U.S Government open data portal.The Retail Sales and Retail use Business Registrations.
# Dataset originates from the State of Iowa and contains information about business registered for retail sales and use tax purposes.It includes business status,location,
# tax type,permit issue dates,and permit cancellation dates.This information is valuable for analyzing business registration patterns,geogaphic
# distribution,tax classifications,and trends in business activity across the state.The dataset provides a reliable source for conducting exploratory data analysis (EDA) and generating insights that can support business and economic decision-making. -->

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Data Cleaning Process

# Load the Data Set

In [ ]:
df=pd.read_csv(r"C:\Users\hp\Downloads\retail_sales_and_retail_use_business_registrations.csv")
df.head()

C:\Users\hp\AppData\Local\Temp\ipykernel_11732\1185444898.py:1: DtypeWarning: Columns (0,10) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(r"C:\Users\hp\Downloads\retail_sales_and_retail_use_business_registrations.csv")

,retail_permit_number,consolidated_number,name_of_business,active_or_inactive_business,tax_type,department_business_code,business_code_description,county_fips_code,registration_county_number,business_location_county,county_name,department_city_code,address_of_the_business,city_location_of_business,state_of_business,business_zip_code,date_permit_was_issued,date_permit_was_cancelled
0,947000263,947000263,UNITED BANK OF IOWA,Inactive,Consumer Use,522110.0,Commercial Banking,19093.0,47.0,47,Ida,2.0,501 2ND ST,IDA GROVE,IA,51445-1304,1932-01-01,2022-06-30
1,147000408,NaN,ARTHUR CITY OF,Active,Retail Sales,221210.0,Natural Gas Distribution,19093.0,47.0,47,Ida,4.0,217 S MAIN ST,ARTHUR,IA,51431-8053,1934-01-01,NaN
2,116000636,NaN,BENNETT CITY OF,Active,Retail Sales,2213.0,"Water, Sewage and Other Systems",19031.0,16.0,16,Cedar,8.0,201 MAIN ST,BENNETT,IA,52721-7710,1934-01-01,NaN
3,195000671,NaN,"BUFFALO CENTER,CITY OF",Active,Retail Sales,2213.0,"Water, Sewage and Other Systems",19189.0,95.0,95,Winnebago,2.0,201 2ND AVE SW,BUFFALO CENTER,IA,50424-0000,1934-01-01,NaN
4,112000643,NaN,CITY OF ALLISON,Active,Retail Sales,9211.0,"Executive, Legislative, and Other General Gove...",19023.0,12.0,12,Butler,5.0,410 N MAIN,ALLISON,IA,50602-0000,1934-01-01,NaN

# Descriptive Analysis

In [ ]:
df.shape

(365478, 18)

In [ ]:
df.dtypes

retail_permit_number            object
consolidated_number             object
name_of_business                object
active_or_inactive_business     object
tax_type                        object
department_business_code       float64
business_code_description       object
county_fips_code               float64
registration_county_number     float64
business_location_county         int64
county_name                     object
department_city_code           float64
address_of_the_business         object
city_location_of_business       object
state_of_business               object
business_zip_code               object
date_permit_was_issued          object
date_permit_was_cancelled       object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365478 entries, 0 to 365477
Data columns (total 18 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   retail_permit_number         365478 non-null  object
 1   consolidated_number          208296 non-null  object
 2   name_of_business             365478 non-null  object
 3   active_or_inactive_business  365478 non-null  object
 4   tax_type                     365478 non-null  object
 5   department_business_code     296631 non-null  float64
 6   business_code_description    296631 non-null  object
 7   county_fips_code             267754 non-null  float64
 8   registration_county_number   365360 non-null  float64
 9   business_location_county     365478 non-null  int64
 10  county_name                  249091 non-null  object
 11  department_city_code         249091 non-null  float64
 12  address_of_the_business      365468 non-null  object
 13  city_location_of_business    365428 non-null  object
 14  state_of_business            364424 non-null  object
 15  business_zip_code            364708 non-null  object
 16  date_permit_was_issued       365478 non-null  object
 17  date_permit_was_cancelled    125545 non-null  object
dtypes: float64(4), int64(1), object(13)
memory usage: 50.2+ MB

In [ ]:
# Handling Missing Values

In [ ]:
df.isnull().sum()

retail_permit_number                0
consolidated_number            157182
name_of_business                    0
active_or_inactive_business         0
tax_type                            0
department_business_code        68847
business_code_description       68847
county_fips_code                97724
registration_county_number        118
business_location_county            0
county_name                    116387
department_city_code           116387
address_of_the_business            10
city_location_of_business          50
state_of_business                1054
business_zip_code                 770
date_permit_was_issued              0
date_permit_was_cancelled      239933
dtype: int64

In [ ]:
# missing values in numerical columns

In [ ]:
num_cols=df.select_dtypes(include=['float64','int64']).columns
for col in num_cols:
    df[col].fillna(df[col].median(),inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_11732\1336701965.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(),inplace=True)
C:\Users\hp\AppData\Local\Temp\ipykernel_11732\1336701965.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(),inplace=True)
C:\Users\hp\AppData\Local\Temp\ipykernel_11732\1336701965.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(),inplace=True)

In [ ]:
# missing values in categorical columns

In [ ]:
cat_cols=df.select_dtypes(include=['object','category']).columns
for col in cat_cols:
    df[col].fillna(df[col].mode()[0],inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_11732\3886738920.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0],inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365478 entries, 0 to 365477
Data columns (total 18 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   retail_permit_number         365478 non-null  object
 1   consolidated_number          365478 non-null  object
 2   name_of_business             365478 non-null  object
 3   active_or_inactive_business  365478 non-null  object
 4   tax_type                     365478 non-null  object
 5   department_business_code     365478 non-null  float64
 6   business_code_description    365478 non-null  object
 7   county_fips_code             365478 non-null  float64
 8   registration_county_number   365478 non-null  float64
 9   business_location_county     365478 non-null  int64
 10  county_name                  365478 non-null  object
 11  department_city_code         365478 non-null  float64
 12  address_of_the_business      365478 non-null  object
 13  city_location_of_business    365478 non-null  object
 14  state_of_business            365478 non-null  object
 15  business_zip_code            365478 non-null  object
 16  date_permit_was_issued       365478 non-null  object
 17  date_permit_was_cancelled    365478 non-null  object
dtypes: float64(4), int64(1), object(13)
memory usage: 50.2+ MB

In [ ]:
df.isnull().sum()

retail_permit_number           0
consolidated_number            0
name_of_business               0
active_or_inactive_business    0
tax_type                       0
department_business_code       0
business_code_description      0
county_fips_code               0
registration_county_number     0
business_location_county       0
county_name                    0
department_city_code           0
address_of_the_business        0
city_location_of_business      0
state_of_business              0
business_zip_code              0
date_permit_was_issued         0
date_permit_was_cancelled      0
dtype: int64

In [ ]:
# Check duplicate records
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 4

In [ ]:
# Remove duplicate records
df = df.drop_duplicates()
print("Number of duplicate rows after cleaning:", df.duplicated().sum())

Number of duplicate rows after cleaning: 0

In [ ]:
df.columns

Index(['retail_permit_number', 'consolidated_number', 'name_of_business',
       'active_or_inactive_business', 'tax_type', 'department_business_code',
       'business_code_description', 'county_fips_code',
       'registration_county_number', 'business_location_county', 'county_name',
       'department_city_code', 'address_of_the_business',
       'city_location_of_business', 'state_of_business', 'business_zip_code',
       'date_permit_was_issued', 'date_permit_was_cancelled'],
      dtype='object')

In [ ]:
# Fill missing values (NaN) with the previous non-missing value in the column

In [ ]:
df['date_permit_was_cancelled'] = df['date_permit_was_cancelled'].ffill()
df['consolidated_number'] = df['consolidated_number'].ffill()

In [ ]:
df['business_zip_code']=df['business_zip_code'].ffill()

In [ ]:
# Data type conversion

In [ ]:
df['retail_permit_number'] = pd.to_numeric(
    df['retail_permit_number'],
    errors='coerce'
).astype('Int64')

df['consolidated_number'] = pd.to_numeric(
    df['consolidated_number'],
    errors='coerce'
).astype('Int64')

df['business_zip_code'] = pd.to_numeric(
    df['business_zip_code'],
    errors='coerce'
).astype('Int64')

In [ ]:
# Object Datatype change to Numeric

In [ ]:
# convert date column

In [ ]:
df['date_permit_was_issued'] = pd.to_datetime(
    df['date_permit_was_issued'],
    errors='coerce'
)

df['date_permit_was_cancelled'] = pd.to_datetime(
    df['date_permit_was_cancelled'],
    errors='coerce'
)

In [ ]:
df.dtypes

retail_permit_number                    Int64
consolidated_number                     Int64
name_of_business                       object
active_or_inactive_business            object
tax_type                               object
department_business_code              float64
business_code_description              object
county_fips_code                      float64
registration_county_number            float64
business_location_county                int64
county_name                            object
department_city_code                  float64
address_of_the_business                object
city_location_of_business              object
state_of_business                      object
business_zip_code                       Int64
date_permit_was_issued         datetime64[ns]
date_permit_was_cancelled      datetime64[ns]
dtype: object

In [ ]:
# Descriptive statistics for the numerical columns

In [ ]:
df.describe()

,retail_permit_number,consolidated_number,department_business_code,county_fips_code,registration_county_number,business_location_county,department_city_code,business_zip_code,date_permit_was_issued,date_permit_was_cancelled
count,365478.0,365478.0,365478.000000,365478.000000,365478.000000,365478.000000,365478.000000,365478.0,365478,365478
mean,262961187.206634,165055134.962466,332195.128757,19112.522592,38.835509,41.252861,2.363590,51062.087414,2014-08-26 19:30:34.544349952,2021-12-14 02:18:55.324150784
min,2.0,2.0,238.000000,19001.000000,0.000000,0.000000,1.000000,0.0,1900-10-01 00:00:00,1959-01-02 00:00:00
25%,157048550.0,7787.0,7225.000000,19095.000000,0.000000,0.000000,1.000000,51063.0,2009-09-21 00:00:00,2021-11-11 00:00:00
50%,200158438.0,9597.0,423390.000000,19115.000000,33.000000,42.000000,1.000000,51063.0,2019-02-01 00:00:00,2021-11-11 00:00:00
75%,305607115.75,304300528.5,459120.000000,19153.000000,77.000000,77.000000,2.000000,51063.0,2023-01-02 00:00:00,2021-11-11 00:00:00
max,999000426.0,999000426.0,928120.000000,19197.000000,99.000000,99.000000,21.000000,99223.0,2027-04-01 00:00:00,2027-02-28 00:00:00
std,191718423.379178,214427010.54605,254166.462343,47.451363,34.527198,34.401550,2.966247,1716.766592,NaN,NaN

In [ ]:
# Cleaned Dataset saved to csv file

In [ ]:
df.to_csv("cleaned_dataset_retail_business_data.csv", index=False)